cmake .. \
-DCMAKE_INSTALL_PREFIX=$HIPSYCL_INSTALL \
-DCMAKE_BUILD_TYPE=Release \
-DBOOST_ROOT=$BOOST_ROOT/ \
-DLLVM_DIR=$LLVM_PATH/lib/cmake/llvm \
-DROCM_PATH=$ROCM_PATH/ \
-DWITH_ROCM_BACKEND=ON

#without CPU
cmake .. -DCMAKE_INSTALL_PREFIX=$HIPSYCL_INSTALL -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=$BOOST_ROOT/ -DROCM_PATH=$ROCM_PATH/ -DWITH_ACCELERATED_CPU=OFF
make -j 8