[problem]
nx  = 32
nvx = 32
ny  = 32
nvy = 32

dt  = 0.001

minX  = 0
maxX  = 1
minVx = -1
maxVx = 1
minY  = 0
maxY  = 1
minVy = -1
maxVy = 1

[optimization]
# The kernel type to use for advection
gpu     = true
# Size of work groups use in the kernels
pref_wg_size = 512

